#!/bin/bash
gcc -std=gnu99 -o enc_server server.c -DENCODE
gcc -std=gnu99 -o enc_client client.c -DENCODE

gcc -std=gnu99 -o dec_server server.c
gcc -std=gnu99 -o dec_client client.c

gcc -std=gnu99 -o keygen keygen.c
